name: Test Suite

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        include:
          - os: windows-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 2.7

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Install with test dependencies
      shell: bash
      run: |
        pip install -e .
        python -m pip install -r requirements-test.txt
    - name: Install ffmpeg and imagemagick (extra test dependencies)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg imagemagick
    - name: Run test suite
      run: |
        py.test tests/
    - name: Check with flake8
      run: |
        python -m pip install flake8
        python -m flake8 vc2_conformance tests
    - name: Check black code style used
      if: ${{ matrix.python-version != 2.7 }}
      run: |
        python -m pip install black
        python -m black --check vc2_conformance tests
