name: Check docs build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Install doc dependencies
      run: |
        # Not yet available on PyPA
        pip install "vc2_conformance_data @ https://github.com/bbc/vc2_conformance_data/releases/download/v1.0.0/vc2_conformance_data.tar.gz"
        pip install -e .
        python -m pip install -r requirements-docs.txt
        sudo apt-get update -y
        sudo apt-get install -y \
          inkscape \
          latexmk \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended
    - name: Build documentation
      run: |
        make -C docs/ html latexpdf
